Update in help file template
projectatomic/container-best-practices pull request #109
Opened 2017-07-12 11:02 UTC by rpitonak

- More detailed help file, helps user to better understand how to use image.
- ENVIROMENT VARIABLES heading to specify how to run the image in different ways without the need of rebuilding image.

Example help file for Perl s2i image: https://raw.githubusercontent.com/container-images/perl/master/root/help.md

2017-07-12 11:54 UTC, eliskasl reviewed
Just a few grammar corrections :) Otherwise looks good!

2017-07-12 11:54 UTC, eliskasl commented on creating/help.adoc
>  If you image uses any privileges that you want to make the user aware of, be sure to document which ones are used and optionally
If your image...

2017-07-12 11:54 UTC, eliskasl commented on creating/help.adoc
> +Describe LABEL settings (from the Dockerfile that created the image) that contains pertinent information.
...that contain...

2017-07-12 11:54 UTC, eliskasl commented on creating/help.adoc
> +Also, describe default configuration options (when defined): hostname, domainname, user ID run as, exposed ports, volumes, working directory, command run by default, etc.
...the default...

2017-07-12 11:54 UTC, eliskasl commented on creating/help.adoc
> +Explain all environment variables available to run the image in different ways without the need of rebuilding the image. Change variables on the docker command line with -e option. For example:
...all the...

2017-07-12 11:54 UTC, eliskasl commented on creating/help.adoc
> +    Opens  container  port  3306  and  maps it to the same port on the Host.
A few duplicated spaces between words.

2017-07-12 11:54 UTC, TomasTomecek requested changes
I'm not sure about guidelines and writing style, I just provided comments to content.

2017-07-12 11:54 UTC, TomasTomecek commented on creating/help.adoc
> +Describe how image is used (user app, service, base image, builder image, etc.), the services or features it provides, and environment it is intended to run in (stand-alone docker, atomic super-privi
Can we stick to the former description?

I would incorporate your changes like this:

    Describe in greater detail the role or purpose of the image (application, service, base image, builder image, etc.).

I'm not sure how to incorporate the sentence about environment (is it even relevant?).

2017-07-12 11:54 UTC, TomasTomecek commented on creating/help.adoc
> +For containers run by atomic, that could include INSTALL, RUN, UNINSTALL, and UPDATE LABELS. Others could
I'm not sure if it's relevant to describe labels such as name, version, release...

2017-07-12 11:54 UTC, TomasTomecek commented on creating/help.adoc
> +Also, describe default configuration options (when defined): hostname, domainname, user ID run as, exposed ports, volumes, working directory, command run by default, etc.
hostname, domain name are irrelevant, right? I would change "user ID run as" to "default user", same for "command run by default" -- "default command".

2017-07-12 11:54 UTC, TomasTomecek commented on creating/help.adoc
> +If you expose ports or run with privileges, note those and provide an explanation. For example:
can we get better examples here? E.g. postfix requires root, dhcp-client requires capability to manage networking.

2017-07-12 11:54 UTC, TomasTomecek commented on creating/help.adoc
> +Does Red Hat provide MariaDB technical support on RHEL 7? https://access.redhat.com/solutions/1247193
I would also point to upstream documentation (git repository of some image on github).

2017-07-12 12:02 UTC, eliskasl commented on creating/help.adoc
> +Describe LABEL settings (from the Dockerfile that created the image) that contains pertinent information.
One more thing, a link to the label repo could be useful: https://github.com/projectatomic/ContainerApplicationGenericLabels/tree/master/vendor/redhat

2017-07-14 10:16 UTC, rpitonak commented
Updated, please have another look.

2017-07-14 10:58 UTC, TomasTomecek requested changes
Just one nit, otherwise looks good. Nice work!

2017-07-14 10:58 UTC, TomasTomecek commented on creating/help.adoc
> +-d
Can we remove this item? I don't understand how it is a security concern.

2017-07-17 09:41 UTC, merged